{% set name = "merge-stardist-masks" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/merge_stardist_masks-{{ version }}.tar.gz
  sha256: fe65e80a49e002a25e6e1b962813ac6909a652b49025c1fcda69136019a9d0e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - edt >=2.3.0,<3.0.0
    - numpy >=1.21.0
    - python >={{ python_min }},<3.10
    - stardist >=0.7.3,<0.9.0

test:
  imports:
    - merge_stardist_masks
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gatoniel/merge-stardist-masks
  summary: Merge Stardist Masks
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
